name: Hugo

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.58.3'
        # extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy
      run: |
          cd public/
          git init
          git config user.name "airdb-bot"
          git config user.email "airdb-bot@airdb.com"
          git add -A
          git commit -m "Auto Update by actions"
          git push --force "https://${{ secrets.GithubBotToken }}@github.com/${{ github.repository }}" master:gh-pages
